name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Vercel (via API)
        run: |
          curl -X POST https://api.vercel.com/v13/deployments \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -F "projectId=${{ secrets.VERCEL_PROJECT_ID }}" \
          -F "orgId=${{ secrets.VERCEL_ORG_ID }}" \
          -F "files=@./"  
